= Git Workshop
:icons:
:toc: macro
:toc-title:
:toclevels:

toc::[]

== Introduction

This is a sample repository to demonstrate Git and handling of merge conflicts.

[NOTE]
====
Kevin might be late to this workshop. In that case, enjoy the lessons contained in this sample repository about how to write words good.
====

== Creating and handling merge conflicts

* We're going to create merge conflicts in this repository during the workshop.
This is intended, and is part of why there are numerous typos.

To create some conflicts:

. Make some form of change to this file and commit your changes.
Once everyone has made some kind of change and committed it, we'll update this file remotely.

. Once the file has been updated, try pulling the new changes:
+
----
$ git pull
----

. You should encounter merge conflicts because I'll  change almost every line of this file in some way or another.

. This will give us the opportunity to work through the merge conflicts during the workshop and hopefully end up with a much nicer repository.

== References

A lot of the information that we'll be going over today is also documented in my Avoiding Merge Conflicts (link:https://github.com/robin-owen/avoiding-merge-conflicts[robin-owen/avoiding-merge-conflicts]) repository on GitHub.
